spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Cris49302@123
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true

server:
  tomcat:
    use-relative-redirects: true
